---
title: "ENA Test"

author: "Author: Zhuni Excel & Jonathon Sun"
date: "`r { x <- params$render_generated_at; if (length(x) == 1 && !is.na(x) && nzchar(trimws(as.character(x)))) { x <- trimws(as.character(x)); x_date <- sub('^([0-9]{4}-[0-9]{2}-[0-9]{2}).*$', '\\\\1', x); if (grepl('^[0-9]{4}-[0-9]{2}-[0-9]{2}$', x_date)) paste0('Report Date: ', x_date) else paste0('Report Date: ', format(Sys.Date(), '%Y-%m-%d')) } else paste0('Report Date: ', format(Sys.Date(), '%Y-%m-%d')) }`"
output:
  html_document:
    self_contained: true
    toc: true
    toc_float: true
    toc_depth: 3
params:
  talent: "Ava"
  data_source: "staging"
  data_root: null
  render_generated_at: null
  included_date_range: null
  render_cli: null
  render_output_dir: null
  render_output_prefix: null
  include_interpretations: true
  window_days: null
  start_date: null
  end_date: null
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(
  echo     = FALSE,
  message  = FALSE, 
  warning  = FALSE,
  fig.align = "center"
)

plot_w_std <- 10
plot_h_std <- 6
plot_w_facet <- 11
plot_h_facet <- 8
plot_w_dense <- 12
plot_h_dense <- 8

knitr::opts_knit$set(root.dir = here::here())

if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(
    fig.width  = 14,
    fig.height = 8,
    out.width  = "0.8\\linewidth"
  )
} else {
  knitr::opts_chunk$set(
    fig.width  = plot_w_std,
    fig.height = plot_h_std
  )
}


```

```{r libraries, include=FALSE}

library(tidyverse)
library(purrr)
library(here)
library(ggplot2)
library(DT)
library(plotly)

```

```{r report_layout_style, echo=FALSE, results='asis'}
cat(
  "<style>
  .main-container {
    max-width: 1200px !important;
  }
  .section.level1,
  .section.level2,
  .section.level3 {
    max-width: 100%;
    overflow-x: hidden;
  }
  .html-widget,
  .plotly.html-widget,
  .js-plotly-plot,
  .plot-container,
  .svg-container {
    max-width: 100% !important;
  }
  .plotly.html-widget {
    width: 100% !important;
  }
  .dataTables_wrapper {
    width: 100%;
    max-width: 100%;
  }
  .dataTables_wrapper .dataTables_scroll {
    overflow-x: auto;
  }
  table.dataTable {
    width: 100% !important;
  }
  .dataTables_wrapper table.dataTable thead th,
  .dataTables_wrapper table.dataTable thead td {
    white-space: normal !important;
    line-height: 1.2;
    vertical-align: bottom;
  }
  </style>"
)
```

```{r modules, include=FALSE}

source("r_scripts/lib/utils/staging_root.R")
source("r_scripts/lib/utils/datalake_root.r")

list.files(here("r_scripts","lib","plots","report","bundle_A"), full.names = TRUE) %>%
    walk(source)
list.files(here("r_scripts","lib","utils"), full.names = TRUE) %>%
    walk(source)
list.files(here("r_scripts", "lib", "import_data"), pattern = "[rR]$", full.names = TRUE) %>%
  walk(source)
list.files(here("r_scripts", "lib", "report_tables"), pattern = "[rR]$", full.names = TRUE) %>%
  walk(source)
source(here("r_scripts","lib","plots","PlottingThemes.R"))

clean_data_dir <- here::here("r_scripts", "lib", "clean_data")
source(file.path(clean_data_dir, "analytics_core.R"))
source(file.path(clean_data_dir, "analytics_join.R"))
source(file.path(clean_data_dir, "clean_columns.R"))
source(file.path(clean_data_dir, "video_prep.R"))
source(file.path(clean_data_dir, "title_classification_join.R"))
source(file.path(clean_data_dir, "qualitative_data_prep", "qualitative_data_prep.r"))

```


# Import data 
```{r import_data}

coding_book <- resolve_datalake_path(
  r"(Z:\DataLake\Sun_Data_Analytics\Processed\Talent_Data\qualitative_code_library\selections\code_test\code_test_codebook.csv)"
)

coding_review_path <- resolve_datalake_path(
  r"(Z:\DataLake\Sun_Data_Analytics\Processed\Talent_Data\qualitative_batch_runs\Ava_k84ImiUcjbE_2026-05-20\coding_review.csv)"
)

codebook_data <- readr::read_csv(
  coding_book,
  show_col_types = FALSE
)

import_data <- readr::read_csv(
  coding_review_path,
  show_col_types = FALSE
)

```

